### ISSUE TITLE
Download links of model weights are not available now

### ISSUE THREAD

**Issue by strongwolf** [microsoft/UniCL#11]
All the links are expired now.  Should the weights be only downloaded upon request?

**Comment by Yeon07** [comment]
Hi, thanks for sharing the great work. 
Could you update the weigth links? 
Thanks in advance.

**Comment by jwyang** [comment]
hi, thanks for your interest.

I had put all checkpoints on release: https://github.com/microsoft/UniCL/releases/tag/v1.0
