### ISSUE TITLE
Questions about loss calculation during training

### ISSUE THREAD

**Issue by dzhengxin** [microsoft/UniCL#12]
Hi, sorry to bother you. I have got some questions about the loss calculation during training.
In the paper, it seems that the label size should be [Batch_size * Batch_size], so it can be calculated with the output which is also with size [Batch_size * Batch_size].
But in the code , if the MODEL.NUM_CLASS>2, the the target size after the function mixup_fn became [Batch_size * NUM_CLASS], which will fail at the calculation of loss.
Maybe I missed some thing, this is really confusing me. 
Really appreciate it if you can answer my questions.

**Comment by jwyang** [comment]
Hi, @dzhengxin , this is a great question, we need to specifically take care mixup operation. By default, we do not use mixup for most of our experiments. When equipping with mixup, we developed a strategy to convert the mixup output to Batch_size x Batch_Size matrix by doing the matrix multiplication:

Affinity = mixup_output * mixup_output^T.

thanks,
Jianwei

**Comment by dzhengxin** [comment]
Yes, this is working! Thank you for answering.
