### ISSUE TITLE
Prospective date for code release

### ISSUE THREAD

**Issue by Sreyan88** [microsoft/UniCL#2]
Hi there!

Great paper! Can you please, if possible, let us know a prospective date for code release?

Thank You

**Comment by jwyang** [comment]
Hi, @Sreyan88 ,

we have released the ckpts and evaluation code. Please have a try!

**Comment by sbkim052** [comment]
@jwyang , thanks for sharing this wonderful code and ckpts.
Do you have any plan to share ckpts for text encoder?

**Comment by jwyang** [comment]
Hi, @sbkim052 ,

the text encoder is already in the checkpoints.

thanks,

**Comment by sbkim052** [comment]
Oh, i totally missed out.
@jwyang, thanks for the reply.
