### ISSUE TITLE
cannot find the bi-directionnal contrastive loss.

### ISSUE THREAD

**Issue by Lechatelia** [microsoft/UniCL#6]
Hello， thanks for your great work!  I think this will inspire my work a lot.
However, after checking your released code, I cannot find the bi-directionnal contrastive loss.  
It seems that you used a uni-directional contrastive loss at https://github.com/microsoft/UniCL/blob/main/main.py#L200.
Sorry if I miss this.

**Comment by jwyang** [comment]
Hi, @Lechatelia , 

thanks for your interest in our work. Sorry for the confusion. Currently, our code only supports inference. We will integrate the training code into our codebase later.

thanks,
Jianwei
